services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    ports:
      -  ${POSTGRESQL_LOCAL_PORT}:${POSTGRESQL_DOCKER_PORT}
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_ROOT_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRESQL_USER} -d ${POSTGRESQL_DATABASE}" ]
      interval: 30s
      timeout: 10s
      retries: 3
  app:
    depends_on:
      - postgres
    restart: on-failure
    image: online-book-store
    build: .
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url": "jdbc:postgresql://postgres:${POSTGRESQL_DOCKER_PORT}/${POSTGRESQL_DATABASE}",
      "spring.datasource.username": "${POSTGRESQL_USER}",
      "spring.datasource.password": "${POSTGRESQL_ROOT_PASSWORD}"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"